### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by vittorioorlandi** [VaishaliJain/ethnicIA#1]
Running `Code/R/01_Create_Train_Features_Master_sparse.R` (as mentioned in Step 1 of the `README`) fails because there is no `NameRaceData` subdirectory in the `Data` directory.

**Comment by cynrudin** [comment]
That directory is here: https://users.cs.duke.edu/~cynthia/ethnicIA/Data/NameRaceData/

**Comment by vittorioorlandi** [comment]
Thank you!
